use std::path::PathBuf;

use crate::capabilities::{SelfCorrector, TestGenerator};
use crate::diff::{self, DiffHunk, unified_diff};

#[derive(Debug, Clone)]
pub struct FileChange {
    pub path: PathBuf,
    pub original: String,
    pub modified: String,
    pub diff: Vec<DiffHunk>,
    pub change_type: ChangeType,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ChangeType { NewFile, Modified, Deleted }

#[derive(Debug, Clone)]
pub struct MultiFileOutput {
    pub files: Vec<FileChange>,
    pub test_file: Option<FileChange>,
    pub imports_added: Vec<(PathBuf, String)>,
    pub docs_generated: Vec<(PathBuf, String)>,
    pub self_corrections: usize,
    pub errors_fixed: Vec<String>,
}

pub struct CodeGenerator {
    project_root: PathBuf,
}

impl CodeGenerator {
    pub fn new(project_root: PathBuf) -> Self { Self { project_root } }

    pub fn generate_multi_file(&mut self, files: Vec<(PathBuf, String)>, language: &str) -> MultiFileOutput {
        let mut output = MultiFileOutput {
            files: Vec::new(), test_file: None, imports_added: Vec::new(),
            docs_generated: Vec::new(), self_corrections: 0, errors_fixed: Vec::new(),
        };

        for (path, new_content) in &files {
            let original = std::fs::read_to_string(&self.project_root.join(path)).unwrap_or_default();
            let diffs = diff::compute_diff(&original, new_content);

            output.files.push(FileChange {
                path: path.clone(), original: original.clone(), modified: new_content.clone(),
                diff: diffs, change_type: if original.is_empty() { ChangeType::NewFile } else { ChangeType::Modified },
            });

            let (with_imports, imports) = Proposer::resolve_imports(path, new_content, language);
            output.imports_added.extend(imports);

            let (with_docs, docs) = Proposer::add_docs(path, &with_imports, language);
            output.docs_generated.extend(docs);

            std::fs::write(&self.project_root.join(path), &with_docs).ok();

            if let Err((error, _)) = SelfCorrector::run_compile_check(&self.project_root) {
                output.errors_fixed.push(format!("compile: {error}"));
                output.self_corrections += 1;
            }
        }

        let test_path = match language {
            "rust" => PathBuf::from("src/tests.rs"), "go" => PathBuf::from("main_test.go"),
            _ => PathBuf::from("test_generated.test"),
        };
        let test_content = TestGenerator::generate_test_for(
            &test_path.to_string_lossy(), &files.iter().map(|(_, c)| c.as_str()).collect::<Vec<_>>().join("\n"), language);
        let test_diff = diff::compute_diff("", &test_content);
        output.test_file = Some(FileChange {
            path: test_path, original: String::new(), modified: test_content.clone(),
            diff: test_diff, change_type: ChangeType::NewFile,
        });

        output
    }
}

pub struct Proposer;

impl Proposer {
    pub fn generate_merge_pr(files: &[FileChange], title: &str, description: &str) -> String {
        let mut pr = format!("# {title}\n\n{description}\n\n## Changes\n\n| File | Type |\n|------|------|\n");
        for file in files {
            let kind = match file.change_type { ChangeType::NewFile => "🆕", ChangeType::Modified => "✏️", ChangeType::Deleted => "🗑️" };
            pr.push_str(&format!("| {} | {kind} |\n", file.path.display()));
        }
        pr.push_str("\n## Diff\n\n```diff\n");
        for file in files { pr.push_str(&unified_diff(&file.diff)); pr.push_str("\n"); }
        pr.push_str("\n```\n\n---\n*Generated by KontroCode*\n");
        pr
    }

    fn resolve_imports(path: &PathBuf, code: &str, language: &str) -> (String, Vec<(PathBuf, String)>) {
        let has_import = code.contains("use ") || code.contains("import ") || code.contains("from ");
        if has_import { return (code.to_string(), vec![]); }
        let default = match language {
            "rust" => "use std::io;\n", "python" => "import os\n",
            "javascript" => "import { readFile } from 'fs';\n",
            _ => "",
        };
        if default.is_empty() { return (code.to_string(), vec![]); }
        let resolved = format!("{default}{code}");
        (resolved, vec![(path.clone(), default.to_string())])
    }

    fn add_docs(path: &PathBuf, code: &str, language: &str) -> (String, Vec<(PathBuf, String)>) {
        let comment = match language { "rust"|"go"|"dart" => "///", "python" => "    \"\"\"", _ => "///" };
        if code.contains(comment) { return (code.to_string(), vec![]); }
        let mut result = code.to_string();
        for line in code.lines() {
            let t = line.trim();
            if (t.starts_with("fn ") || t.starts_with("pub fn ") || t.starts_with("func ")) && !t.starts_with("//") {
                let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
                let name = t.split('(').next().unwrap_or("").split_whitespace().last().unwrap_or("unknown");
                let doc = format!("{indent}{comment} {name} — Generated by KontroCode.\n");
                result = result.replacen(line, &format!("{doc}{line}"), 1);
                return (result, vec![(path.clone(), name.to_string())]);
            }
        }
        (result, vec![])
    }

    pub fn official_pattern_enforce(code: &str, language: &str) -> Vec<String> {
        let mut warnings = Vec::new();
        if (language == "flutter" || language == "dart") && code.contains("setState") && !code.contains("Riverpod") {
            warnings.push("Consider Riverpod over setState".into());
        }
        if language == "rust" && code.contains(".unwrap()") && !code.contains("// safe") {
            warnings.push("Avoid .unwrap() — use ? or proper error handling".into());
        }
        if (language == "javascript" || language == "typescript") && code.contains(": any") && !code.contains("// intentional") {
            warnings.push("Avoid 'any' type — use proper TypeScript types".into());
        }
        warnings
    }
}
